// <auto-generated />
using System;
using DotnetToLambda.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotnetToLambda.Core.Infrastructure.Migrations
{
    [DbContext(typeof(BookingContext))]
    partial class BookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DotnetToLambda.Core.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<string>("ChargeId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConfirmedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("CustomerId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("OutboundFlightId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BookingId")
                        .HasName("PK_BookingId");

                    b.HasIndex("CustomerId")
                        .HasName("UX_Booking_CustomerId");

                    b.ToTable("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
